import angular from 'angular';

// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appFactory from './factory/app.factory';
import appRun     from './config/app.run';
import 'angular-ui-router';
// Import our templates file (generated by Gulp)
import './config/app.templates';
// Import our app functionaity
import './layout';
import './components';
import './home';
import './profile';
import './article1';
import './article2';
import './article3';
import './article4';
import './article5';
import './article6';
import './article7';
import './article8';
import './article9';
import './article10';
import './article11';
import './article12';
import './services';
import './auth';


// Create and bootstrap application
const requires = [
  'ui.router',
  'templates',
  'app.layout',
  'app.components',
  'app.home',
  'app.profile',
  'app.article1',
  'app.article2',
    'app.article3',
    'app.article4',
    'app.article5',
    'app.article6',
    'app.article7',
    'app.article8',
    'app.article9',
    'app.article10',
    'app.article11',
    'app.article12',
  'app.services',
  'app.auth'
];

// Mount on window for testing
window.app = angular.module('app', requires);

angular.module('app').constant('AppConstants', constants);

angular.module('app').config(appConfig);

angular.module('app').run(appRun);

angular.module('app').factory('Base64',appFactory);

angular.bootstrap(document, ['app'], {
  strictDi: true
});
